// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/consumeRateCounter.sql
// source-sha256: cec28c53ae1ba7729883336ca9418b3c45f51ab715ee379f0342b1e11a9ba234
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param key
 * @param windowSeconds
 */
export const consumeRateCounter = $runtime.makeTypedQueryFactory("INSERT INTO rate_counters (key, window_start, count)\nVALUES ($1::text, now(), 1)\nON CONFLICT (key) DO UPDATE\nSET count = CASE WHEN rate_counters.window_start + make_interval(secs => $2::double precision) > now()\nTHEN rate_counters.count + 1\nELSE 1 END,\nwindow_start = CASE WHEN rate_counters.window_start + make_interval(secs => $2::double precision) > now()\nTHEN rate_counters.window_start\nELSE now() END\nRETURNING count, window_start;") as (key: string, windowSeconds: number) => $runtime.TypedSql<consumeRateCounter.Parameters, consumeRateCounter.Result>

export namespace consumeRateCounter {
  export type Parameters = [key: string, windowSeconds: number]
  export type Result = {
    count: number
    window_start: Date
  }
}
