// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/noteLoginFailure.sql
// source-sha256: 580c5bcf6585948dec9f2158c6fc403af9785ec553888c6f3be4e6358ff5a03f
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param key
 * @param lockMinutes
 */
export const noteLoginFailure = $runtime.makeTypedQueryFactory("INSERT INTO login_failures (key, count, until)\nVALUES ($1::text, 1, now() + make_interval(mins => $2::int))\nON CONFLICT (key) DO UPDATE\nSET count = CASE WHEN login_failures.until > now()\nTHEN login_failures.count + 1\nELSE 1 END,\nuntil = now() + make_interval(mins => $2::int),\nupdated_at = now()\nRETURNING count;") as (key: string, lockMinutes: number) => $runtime.TypedSql<noteLoginFailure.Parameters, noteLoginFailure.Result>

export namespace noteLoginFailure {
  export type Parameters = [key: string, lockMinutes: number]
  export type Result = {
    count: number
  }
}
