// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/ping.sql
// source-sha256: a474934f09ce156b55190e5406977a4e9a1eb16482c6e9e9d411eed3e8ee8631
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 */
export const ping = $runtime.makeTypedQueryFactory("SELECT 1 AS ok;") as () => $runtime.TypedSql<ping.Parameters, ping.Result>

export namespace ping {
  export type Parameters = []
  export type Result = {
    ok: number | null
  }
}
