// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/purgeExpiredQueueReports.sql
// source-sha256: 4cc4ce33081f70d207fef301166a58e4a08545875fe155e868c3ef41144b828c
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 */
export const purgeExpiredQueueReports = $runtime.makeTypedQueryFactory("DELETE FROM machine_reports r\nUSING report_settings cfg\nWHERE cfg.id = 1\nAND r.kind = 'queue'\nAND r.created_at <= now() - make_interval(mins => cfg.queue_ttl_minutes)\nRETURNING r.id;") as () => $runtime.TypedSql<purgeExpiredQueueReports.Parameters, purgeExpiredQueueReports.Result>

export namespace purgeExpiredQueueReports {
  export type Parameters = []
  export type Result = {
    id: number
  }
}
