// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/recalcPostStats.sql
// source-sha256: e7539ef217e5c89ab708ab642b5cf8dc6cc08983f5821d3bfbde8636c9bf0b11
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param postId
 */
export const recalcPostStats = $runtime.makeTypedQueryFactory("SELECT true AS done FROM (SELECT recalc_post_stats($1::int)) AS recalc;") as (postId: number) => $runtime.TypedSql<recalcPostStats.Parameters, recalcPostStats.Result>

export namespace recalcPostStats {
  export type Parameters = [postId: number]
  export type Result = {
    done: boolean | null
  }
}
