// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/recalcChartStats.sql
// source-sha256: 91b7b0ec65f945b99f992ccf17683960e983a9cf4386dc701921bee68a996c23
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param chartId
 */
export const recalcChartStats = $runtime.makeTypedQueryFactory("SELECT true AS done FROM (SELECT recalc_chart_stats($1::int)) AS recalc;") as (chartId: number) => $runtime.TypedSql<recalcChartStats.Parameters, recalcChartStats.Result>

export namespace recalcChartStats {
  export type Parameters = [chartId: number]
  export type Result = {
    done: boolean | null
  }
}
