// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/recalcArcadeRating.sql
// source-sha256: 8527631d98955245ee3ef04e42b1fe4271766a2d3edcce220db2237f30d02a64
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param arcadeId
 */
export const recalcArcadeRating = $runtime.makeTypedQueryFactory("SELECT true AS done FROM (SELECT recalc_arcade_rating($1::int)) AS recalc;") as (arcadeId: number) => $runtime.TypedSql<recalcArcadeRating.Parameters, recalcArcadeRating.Result>

export namespace recalcArcadeRating {
  export type Parameters = [arcadeId: number]
  export type Result = {
    done: boolean | null
  }
}
