// 생성물 — 손으로 고치지 마세요. 원본: prisma/sql/tierCharts.sql
// source-sha256: 7d38cb1138eb88f4e084ae23f5225f028725c5c5664ebff97f1bab429e202261
// 다시 만들기: npm run db:prisma:sql (DB 필요) · 대조: npm run db:prisma:sql:check (DB 불필요)

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param playerId
 * @param chartId
 * @param machineId
 * @param mode
 * @param level
 * @param levelUnknown
 * @param versionId
 */
export const tierCharts = $runtime.makeTypedQueryFactory("SELECT c.id, s.title, s.artist, s.machine_id, c.mode, c.difficulty, c.level,\nc.vote_count, c.avg_vote, c.convergence, c.tier_code, c.special_count,\nc.video_url,\n(cr.player_id IS NOT NULL) AS my_clear,\ndv.value AS my_vote,\n(sm.player_id IS NOT NULL) AS my_special\nFROM charts c\nJOIN songs s ON s.id = c.song_id\nLEFT JOIN machine_difficulties md ON md.machine_id = s.machine_id AND md.code = c.difficulty\nLEFT JOIN clear_records    cr ON cr.chart_id = c.id AND cr.player_id = $1::int\nLEFT JOIN difficulty_votes dv ON dv.chart_id = c.id AND dv.player_id = $1::int\nLEFT JOIN special_marks    sm ON sm.chart_id = c.id AND sm.player_id = $1::int\nWHERE ($2::int IS NULL OR c.id = $2::int)\nAND ($3::int IS NULL OR s.machine_id = $3::int)\nAND ($4::text IS NULL OR c.mode = $4::text)\nAND ($5::numeric IS NULL OR c.level = $5::numeric)\nAND (NOT $6::boolean OR c.level IS NULL)\nAND ($7::int IS NULL OR c.version_id = $7::int)\nORDER BY ROUND(c.avg_vote, 2) DESC NULLS LAST,\nCASE WHEN c.avg_vote IS NULL THEN NULL ELSE c.id END ASC NULLS LAST,\ns.title ASC,\nmd.sort_order ASC NULLS LAST,\nc.difficulty ASC NULLS LAST,\nc.mode ASC NULLS LAST;") as (playerId: number | null, chartId: number | null, machineId: number | null, mode: string | null, level: number | null, levelUnknown: boolean, versionId: number | null) => $runtime.TypedSql<tierCharts.Parameters, tierCharts.Result>

export namespace tierCharts {
  export type Parameters = [playerId: number | null, chartId: number | null, machineId: number | null, mode: string | null, level: number | null, levelUnknown: boolean, versionId: number | null]
  export type Result = {
    id: number
    title: string
    artist: string | null
    machine_id: number
    mode: string | null
    difficulty: string | null
    level: $runtime.Decimal | null
    vote_count: number
    avg_vote: $runtime.Decimal | null
    convergence: $runtime.Decimal | null
    tier_code: string | null
    special_count: number
    video_url: string | null
    my_clear: boolean | null
    my_vote: $runtime.Decimal
    my_special: boolean | null
  }
}
