-- ============================================================
-- 005 · Pump It Up 현행 수록곡 목록 (704곡)
--
-- ─── 출처 ───────────────────────────────────────────────
-- 나무위키 (CC BY-NC-SA 2.0 KR)
--   · 펌프 잇 업/수록곡
--   · 펌프 잇 업 PHOENIX 2  (신규 수록곡)
--   · 펌프 잇 업/삭제곡
-- robots.txt 가 /w/ 를 허용하는 문서만 읽었습니다.
--
-- ─── 만든 방식 ──────────────────────────────────────────
--   (수록곡 문서 3.x~9.x  U  PHOENIX 2 신규곡)  -  삭제곡 문서
--
-- 수록곡 문서에서 지역 한정판 4개 섹션은 뺐습니다:
--   3.7  The Premiere            (유럽 & 브라질 전용판)
--   4.2  The Premiere 3          (유럽 전용판)
--   6.5  Infinity                (미국·유럽 전용판)
--   7.1.1 2015 Prime Japanese Edition (일본 한정판)
-- 단, 그 안에서 비고에 '이식' / '본가에서도 플레이 가능' / '동시 수록' 이라고
-- 적힌 곡은 본가에서 플레이 가능하므로 다시 넣었습니다 (27곡).
--
-- ⚠ 알려진 한계 (반드시 읽을 것)
--  1. **난이도 정보가 없습니다.** 세 문서 모두 곡명·아티스트·BPM·추가버전만 있고
--     채보 레벨(S15, D18 …)이 없습니다. 그래서 songs 만 채우고 charts 는 비어
--     있습니다 — 서열표 화면은 여전히 아무것도 안 보입니다. 레벨은 따로 필요합니다.
--  2. **지역 한정판에서 데뷔한 뒤 본가 정착곡이 된 곡 중 일부가 빠집니다.**
--     문서가 '데뷔 버전' 기준으로 정리돼 있고 비고에 이식 표기가 없으면 걸러낼
--     방법이 없습니다. 확인된 누락: Bee (4.2 에만 등장), Mitotsudaira (7.1.1).
--  3. **부활곡이 잘못 빠집니다.** 삭제곡 문서는 '어느 버전에서 삭제됐는지' 만
--     알려주고, 각주에 'PRIME 2에서 부활' 같은 표기가 흩어져 있습니다. 교집합
--     제거는 그 부활을 반영하지 못합니다.
--  4. PHOENIX 2 의 '추후 수록 예정' 5곡은 아직 플레이할 수 없어 뺐습니다.
--  5. **아티스트가 131곡 비어 있습니다(NULL).** 문서 표가 행마다 셀 수가 달라
--     (비고 칸이 비면 아예 빠집니다) 열이 밀린 행이 있습니다. 밀린 값을 아티스트로
--     넣는 것보다 비우는 쪽을 택했습니다 — 그러지 않으면 Canon-D 의 아티스트가
--     '클래식 리메이크, 익시드 2 아케이드 최종보스…' 가 됩니다.
--
-- 되돌리려면: MIGRATION_FILES 에서 이 파일을 빼고 schema_migrations 에서 지운 뒤
--   DELETE FROM songs
--    WHERE machine_id = 1
--      AND id NOT IN (SELECT DISTINCT song_id FROM charts);
--   (채보가 붙지 않은 곡만 지웁니다 = 이 파일로 들어온 곡)
--
-- ⚠ 여러 번 실행해도 결과가 같아야 합니다 (lib/db.ts runMigrations 주석 참고).
-- ============================================================

INSERT INTO songs (machine_id, title, artist)
SELECT 1, v.title, v.artist
FROM (VALUES
  ('!'::text, 'Onyx'::text),
  ('%X', 'Pory'),
  ('* this game does not exist *', 'litmus* x Ester'),
  ('1948', 'SLAM'),
  ('1949', 'SLAM'),
  ('2006. Love Song', 'Banya Production'),
  ('2step Baby', 'U-ske'),
  ('404 (New Era)', 'KiiiKiii'),
  ('4NT', NULL),
  ('80''s pop', 'Energy Presents'),
  ('86', 'Dasu'),
  ('A Little Less Conversation', NULL),
  ('A Prison Without Bars', '박진영'),
  ('A Site De La Rue', 'STREAM REVERIE'),
  ('A Whistle', 'CB Mass'),
  ('About The Universe', NULL),
  ('Accelerator', 'Nitro'),
  ('Accident', 'MAX'),
  ('Achluoias', 'D_AAN'),
  ('Acquire', 'ryhki'),
  ('Adrenaline Blaster', 'QWertism'),
  ('Aleph-0', 'LeaF'),
  ('Alice in Misanthrope', 'LeaF'),
  ('Aliens in Our Midst', 'Corporation'),
  ('ALiVE', 'REDALiCE'),
  ('Allegro Con Fuoco', 'DM Ashura'),
  ('Allegro Furioso', 'DM Ashura'),
  ('Allegro Piu Mosso', 'DM Ashura'),
  ('Altale', 'Sakuzyo'),
  ('Always', '보이클럽'),
  ('Amphitryon', NULL),
  ('Anguished Unmaking', 'void'),
  ('Annihilator Method', NULL),
  ('Another Truth', NULL),
  ('Antique Serenade', 'Abel'),
  ('Anubis', 'Banzai'),
  ('Appassionata', 'Cashew x D_AAN x Jehezukiel'),
  ('Aragami', 'xi'),
  ('Arcana Force', 'MiLa'),
  ('Arch of Darkness', '아크쉐이드 오프닝'),
  ('Arirang', NULL),
  ('Art City', 'Virgill'),
  ('ASDF', NULL),
  ('Asterios-ReEntry', 'ATAS'),
  ('Athena''s Shield', 'Jehezukiel'),
  ('Avalanche', NULL),
  ('Awakening', 'typeMARS'),
  ('B2', NULL),
  ('B3', 'MAX'),
  ('Bad Apple!! feat. nomico', 'Masayoshi Minoshima'),
  ('Bad Character(못된 성질)', NULL),
  ('BANG BANG', 'IVE'),
  ('Barber''s Madness', 'Klass E'),
  ('Baroque Virus', 'Zircon'),
  ('BATTLE NO.1', 'TANO*C Sound Team'),
  ('Be My Friend', 'Lagoona'),
  ('Beat of the war 2', 'BanYa'),
  ('Beat the ghost', '기타맨 부분 샘플링'),
  ('Becouse of You', 'Srav3R & USAO'),
  ('BEDLAM', 'SANY-ON'),
  ('BEE', 'Banya'),
  ('Beethoven Virus', NULL),
  ('Bestest Frenemy!', NULL),
  ('Betrayer', 'BanYa'),
  ('Big Daddy', 'USAO'),
  ('Big Money', 'X-Teen'),
  ('Binary Star', NULL),
  ('Black Dragon', 'Memme'),
  ('Black Swan', 'Zeron'),
  ('Blaze Emotion (Band Version)', NULL),
  ('Blazing', NULL),
  ('BLAZOR', 'WONDERTRAVELER project'),
  ('Blind Faith', 'O-24'),
  ('Blow My Mind', 'Alphadelta'),
  ('Bluish Rose', 'WyvernP'),
  ('Bonaccia', '나스카'),
  ('Boogie Land', 'Le Bruj'),
  ('BOOMERANG', 'Wanna One'),
  ('BOOOM!!', 'RiraN'),
  ('Brain Power', 'NOMA'),
  ('Break It Down', 'MAZO'),
  ('Break Out', 'Ireleriser'),
  ('Break Through Myself feat. Risa Yuzuki', 'DJ Myosuke & Laur'),
  ('Breakin''Love', NULL),
  ('Breathing You In', 'Zircon Feat. Jillian Goldin'),
  ('Bring Back The Beat', 'Lunatic Sounds'),
  ('Broken Karma (PIU Edit)', 'Quree'),
  ('BSPower Explosion', 'YSJ'),
  ('Bullfighter''s Song', NULL),
  ('Burn Out', NULL),
  ('Butterfly', 'MAX&Rorychesell(S.I.D-Sound)'),
  ('Campanella', NULL),
  ('Can-can ~Orpheus in The Party Mix~', 'Sr. Lan Belmont'),
  ('Canon-D', NULL),
  ('CARMEN BUS', 'StaticSphere vs. FUGU SUISAN'),
  ('Certain Victory', NULL),
  ('CHAOS AGAIN', 'NAOKI underground -Ω-'),
  ('Chaotic WHITE', 'DM Ashura vs Enoch'),
  ('Chase Me', '드림캐쳐'),
  ('Chimera', NULL),
  ('Chinese Restaurant', 'Memme'),
  ('Chobit Flavor', 'aran & t+pazolite'),
  ('Chocolate', '바나나걸'),
  ('Chopstix', 'Sonic Dimension'),
  ('Christmas Memories', 'FOX-B'),
  ('Cleaner', 'Doin'),
  ('Clematis Rapsodia', 'Jehezukiel'),
  ('Clockwork Genesis', 'Inspector K'),
  ('Closer to Heaven', 'MePuma'),
  ('Club Night', 'Matduke'),
  ('Clue', 'Transin'),
  ('CO5M1C R4ILR0AD', 'kanone'),
  ('Coalesce', 'On Slot'),
  ('Come On', '이정현'),
  ('Coming Out', 'Playmaker feat. Robin'),
  ('Concerto', 'Sanxion7'),
  ('Cosmic Unconsciousness', 'When Machines Dream'),
  ('Cosmical Rhythm', NULL),
  ('Cowgirl', 'Bambee'),
  ('Crash-Landing Rendezvous', 'Xyris'),
  ('Creamy Skinny', 'BanYa'),
  ('Crimson hood', 'Springhead'),
  ('Cross Over', 'HyuN'),
  ('CROSS RAY', 'HyuN feat. 月下Lia'),
  ('Cross Soul', 'HyuN feat. Syepias'),
  ('Cross Time', 'Brandy'),
  ('CROSSING DELTA', 't+pazolite+ginkiha+Hommarju'),
  ('Crowdpleaser (Drop the Mic Mix)', 'SGX'),
  ('Csikos Post', NULL),
  ('Curiosity', '한스밴드'),
  ('Curiosity Overdrive', 't+pazolite'),
  ('Cycling!', 'Yamajet feat. あまね (COOL&CREATE)'),
  ('Cygnus', 'nato'),
  ('Cynical', 'RiraN feat. Negoto Bunnyla'),
  ('D', '클래식 리믹스'),
  ('Dabbi Doo', 'Ni-Ni'),
  ('Dance with me', NULL),
  ('Dancing', NULL),
  ('Danger & Danger', 'Cranky'),
  ('Darkside Of The Mind', 'DJ Myosuke'),
  ('Dawgs In Da House', 'CanBlaster (Miami Style)'),
  ('Dawn (Perpetual Mix)', 'KaW'),
  ('Dead End', 'Cosmograph'),
  ('Dead Soul', NULL),
  ('Death Moon', 'SHK'),
  ('Deca Dance', 'Yooh'),
  ('Dement -After Legend-', 'Lunatic Sounds'),
  ('Demon of Laplace', 'Quree'),
  ('Destination', 'SHK'),
  ('Destiny', 'Smiley'),
  ('Destr0yer', 'Sakuzyo'),
  ('DESTRUCIMATE', 'KURORAK'),
  ('Dieciseis', 'Nina Pilots'),
  ('Digan Lo Que Digan(나완 상관없어)', NULL),
  ('Digitalis', 'NeLiME'),
  ('Disco Bus', '김현정'),
  ('Disco Punks on Jolt', 'Blue Stahli'),
  ('District 1', 'MAX'),
  ('Dizzy Dance, Street Light', 'WyvernP'),
  ('DJ Superstar', 'Oscillator X'),
  ('Do It!', NULL),
  ('Do What You Wanna Do', 'Playmaker'),
  ('Do you know that - old school', NULL),
  ('Dolly Kiss', NULL),
  ('Don''t Don''t Go Away', 'Foxxie'),
  ('Donatello', 'Triplestar'),
  ('Doppelganger', 'MonstDeath'),
  ('Dr. M', 'BanYa'),
  ('Dream To Nightmare', 'Nightmare'),
  ('Dreamchasers', 's-don'),
  ('Drunken in Melody', '은지원'),
  ('Dual Racing <RED vs BLUE>', 'nato & r300k'),
  ('DUEL', 'Cashew & D_AAN'),
  ('E.O.N', 'HiTECH NINJA'),
  ('Earendel', 'Palami feat. neur6sia'),
  ('Elder God Shrine', 'E-Racer'),
  ('Electrock', 'Throwdown'),
  ('Elise', 'DM Ashura'),
  ('Elysium', NULL),
  ('EMOMOMO', 'Ras'),
  ('Emperor', NULL),
  ('ENERGY SYNERGY MATRIX', 'Tanchiky'),
  ('Enjoy The Show', 'RiraN ft. Negoto Bunnyla'),
  ('Epilogue', 'When Machines Dream'),
  ('Ercitite', 'Doin x neur6sia'),
  ('ESCAPE', 'D_AAN'),
  ('ESP', NULL),
  ('Esperanza', 'KaW'),
  ('Eternal Universe', NULL),
  ('EternuS', 'Sanxion7'),
  ('Etude Op 10-4', 'MAX'),
  ('Euphoria', 'KaW feat. Smiley'),
  ('Euphorianic', 'SHK'),
  ('Exotica', 'Banzai'),
  ('Extravaganza', NULL),
  ('F(R)IEND', 'D_AAN'),
  ('Fairy Dash', NULL),
  ('Fallen Angel', 'DM Ashura ft. Ariel'),
  ('Faster Z', NULL),
  ('Feel My Happiness', NULL),
  ('Feels Just Like That Night', 'Eskimo & Icebird feat. Maria Merete'),
  ('Ferry Boat', 'DJ DOC'),
  ('Festival of Death Moon', NULL),
  ('Fever', '조PD'),
  ('FFF (Flew Far Faster)', 'Doin'),
  ('Final Audition', '장수곡, 히든곡, Extravaganza 출현 조건 대상곡.'),
  ('Final Audition 2', 'BanYa'),
  ('Final Audition 3 U.F (Un.Finished)', 'BanYa'),
  ('Final Audition Episode 1', 'BanYa'),
  ('Final Audition Episode 2-1', 'Yahpp'),
  ('Final Audition Episode 2-2', NULL),
  ('Fires of Destiny', 'Jehezukiel'),
  ('First Love (Spanish ver.)', NULL),
  ('First Love (Techno Mix)', '클론'),
  ('Flavor Step!', 'EmoCosine'),
  ('Flower Night', '피플크루'),
  ('FLVSH OUT', 'Getty'),
  ('Follow Me', 'SHK'),
  ('Force of Ra', NULL),
  ('Forgotten Vampire', 'WyvernP'),
  ('Fracture Temporelle', NULL),
  ('FREEDOM DiVE', 'xi'),
  ('Frozen', 'Celldweller'),
  ('Full Moon', '드림캐쳐'),
  ('Funk Factory', 'Money Deluxe'),
  ('Funky Jockey', 'B.O.K'),
  ('Further', 'Doin'),
  ('Galaxy Collapse', NULL),
  ('Gargoyle', 'Sanxion7'),
  ('Gentleman Quality', NULL),
  ('Get Up (And Go)', NULL),
  ('Ghroth', 'nato'),
  ('Giselle', 'Sobrem a.k.a Widowmaker'),
  ('Glimmer Gleam', 'BAMI & Siesphere'),
  ('GLORIA', 'Croire'),
  ('GO! (EK Mix)', 'DM Ashura'),
  ('God Mode 2.0 feat. Skizzo', NULL),
  ('God Mode feat. Skizzo', 'nato'),
  ('Good Night', '드림캐쳐'),
  ('GOODBOUNCE', 'EBIMAYO'),
  ('GOODTEK', 'EBIMAYO'),
  ('Gothique Resonance', 'P4koo'),
  ('Groovin'' Motion', 'Sonic Dimension'),
  ('Gun Rock', '익시드 2 오프닝 리믹스'),
  ('Halcyon', 'yama_ko'),
  ('Halloween Party ~Multiverse~', 'KimAutomne'),
  ('Hanky Panky', 'Jenny Rom'),
  ('Hardkore Atomic', 'Diclonius Kid'),
  ('Hardkore of the North', 'Diclonius Kid'),
  ('Harmagedon', 'HyuN vs lixound'),
  ('Hasse Mich', 'Onyx'),
  ('Haven', 'SGX'),
  ('Hayuga', NULL),
  ('Headless Chicken', 'r300k'),
  ('Heart Attack', 'DJ Counterforce'),
  ('Heart Break', '조성모'),
  ('HEART RABBIT COASTER', 'nato'),
  ('Heliosphere', 'BlackY'),
  ('HELIX', 'ESTi'),
  ('Hell Flame', 'Diclonius Kid'),
  ('Hellfire', 'Memme'),
  ('Hello William', NULL),
  ('Hercules', 'Abel'),
  ('Hestia', 'Gentle Stick'),
  ('Hey U', 'MAZO'),
  ('Hi-Bi', NULL),
  ('Highway Chaser', NULL),
  ('Holiday', 'F2 Original'),
  ('Houseplan', 'Houseplan'),
  ('HTTP', 'YSJ'),
  ('Human Extinction (PIU Edit)', NULL),
  ('Hungarian Dance V', 'Banya Production'),
  ('HUSH', NULL),
  ('Hyacinth', NULL),
  ('Hymn of Golden Glory', 'Essbee'),
  ('Hypercube', 'MAX'),
  ('Hyperion', 'M2U'),
  ('Hypnosis (Synthwulf Mix)', 'BanYa remixed by Synthwulf'),
  ('I am Your Girl', NULL),
  ('I Don''t Know Anything', '엄정화'),
  ('I Know', '서태지와 아이들'),
  ('I Love You', '쥬얼리'),
  ('I Think I Like That Sound', 'Kid Whatever'),
  ('I Want U', '드렁큰 타이거'),
  ('I Will Accept You', '박지윤'),
  ('I Yah', 'H.O.T.'),
  ('I''ll Give You All My Love', '왁스'),
  ('I''m Just a DJ', 'Ekowraith feat. Kyrn'),
  ('Ice of Death', 'Fiverwater'),
  ('Ignis Fatuus', 'BanYa remixed by DM Ashura'),
  ('Ika Uka', 'Jenny Rom'),
  ('Imaginarized City', 'Reku Mochizuki'),
  ('Imagination', 'SHK'),
  ('Imperium', 'Sakuzyo'),
  ('Imprinting', 'Sakuzyo'),
  ('In The Groove', 'One Dollar'),
  ('In The Night', 'Scandalous'),
  ('Incognito', 'Inspector K'),
  ('Indestructible', 'Matduke'),
  ('Infection', 'Inspector K'),
  ('INFiNiTE ENERZY -Overdoze-', 'Reku Mochizuki'),
  ('INFINITY', 'Lunatic Sounds'),
  ('Interference', NULL),
  ('Into My Dream -Kaveh Azizi remix-', 'Lagoona'),
  ('INVASION', 'D_AAN'),
  ('Iolite Sky', 'Doin'),
  ('iRELLiA', 'HyuN'),
  ('It''s My Party', NULL),
  ('It''s Over Now', 'Virgill'),
  ('J-Bong', 'BanYa'),
  ('JANUS', 'MAX'),
  ('Jonathan''s Dream', 'MAX&Seorryang(S.I.D-Sound)'),
  ('July -Euromix-', 'js14'),
  ('Jupin', 'Sobrem'),
  ('Just A Girl', NULL),
  ('Just hold on(To All Fighters)', 'void'),
  ('Karyawisata', 'Vesuvia x REDSHIFT'),
  ('Kasou Shinja', 'MiLa'),
  ('Katkoi', NULL),
  ('Keep On!', 'AmamoriP'),
  ('Kill Them!', 'Archefluxx & Kesean Beat'),
  ('Kimchi Fingers', 'Garlic Squad'),
  ('King of the Beats', 'Throwdown'),
  ('King''s Tomb', 'r300k'),
  ('Kiss', '컨츄리꼬꼬'),
  ('Kitty Cat', 'Coconut'),
  ('KUGUTSU', 'onoken'),
  ('La Cinquantaine', 'Pory'),
  ('Lacrimosa', 'Fiverwater'),
  ('Ladybug', 'Coconut'),
  ('Lala', 'Yassi Pressman'),
  ('Last Rebirth', 'SHK'),
  ('Latino Virus', 'Warak'),
  ('Le Grand Bleu', 'KIEN'),
  ('Le Grand Rouge', 'KIEN'),
  ('Le Nozze di Figaro ~Celebrazione Remix~', 'Sr. Lan Belmont'),
  ('Leakage Voltage', 'Doin'),
  ('Legendary Dominion', 'Laur'),
  ('Lepton Strike', 'nato'),
  ('Let''s Boogie', '거북이'),
  ('Let''s Get the Party Started', NULL),
  ('Let''s Groove', NULL),
  ('Life is PIANO', 'Junk'),
  ('Lifestreaming', NULL),
  ('Like Me', 'SHK'),
  ('Little Munchkin', 'Castellia'),
  ('Log-in', 'SHK'),
  ('Lohxia', 'The Musical Ghost'),
  ('LOKI', 'Lotze'),
  ('Lolitabot', 'Lolitabot'),
  ('London Bridge', 'Sci GUYS'),
  ('Love', 'S.E.S.'),
  ('Love Eternal', 'When Machines Dream'),
  ('Love is A Danger Zone', NULL),
  ('Love is A Danger Zone (Cranky Mix)', 'BanYa remixed by Cranky'),
  ('Love is A Danger Zone pt.2', NULL),
  ('Lover''s Grief', 'god'),
  ('Lucid (PIU Edit)', 'yak_won'),
  ('Lucid Dream', 'Leful & Simono'),
  ('Lucky Star', 'INFX feat. Miori Celesta'),
  ('Macaron Day', 'HyuN'),
  ('Mad5cience', NULL),
  ('Magical Vacation', 'S.I.D-Sound'),
  ('Mahika', 'The Musical Ghost'),
  ('Man & Woman', '쿨'),
  ('Man vs Mountain', 'Throwdown'),
  ('Maria', NULL),
  ('Maslo', 'Vospi'),
  ('Master of Puppets', NULL),
  ('Matador', 'Cranky'),
  ('MEGAHEARTZ', 'DJ Noriken'),
  ('Memory', 'On Slot'),
  ('Mental Rider', 'SQUAR'),
  ('Meteorize', 'Paul Bazooka'),
  ('Midnight Blue', NULL),
  ('MilK', 'モリモリあつし'),
  ('Milky Way Galaxy', '3R2'),
  ('Mind Your Matter', 'Bjorn Fogelberg'),
  ('Miss S'' Story', NULL),
  ('Mission Incredible', 'Bjorn Lynne'),
  ('Moment Day', NULL),
  ('Monkey Fingers', NULL),
  ('Monkey Magic', '이박사'),
  ('Monolith', 'Affinity'),
  ('Moonlight', NULL),
  ('Moonshard', 'Triplestar'),
  ('Moonstone', 'Virgill'),
  ('Mopemope', 'LeaF'),
  ('Move It Groove It', 'KaW feat. Sam-I-Am'),
  ('Move That Body!', 'DM Ashura feat. Skizzo & Hanna'),
  ('Move Your Head', '틴틴파이브'),
  ('Mr.Larpus', '본작 출시 전 선공개된 음원, S/E 최종 보스'),
  ('MURDOCH', 'WONDERTRAVELER Project'),
  ('Murdoch vs Otada', 'ESPITZ vs WONDERTRAVELER Project'),
  ('Music', NULL),
  ('My Best Day Is Gone', '캔'),
  ('My Fantasy', NULL),
  ('Nade Nade', 'Doin'),
  ('Naissance', '히든곡'),
  ('Naissance 2', NULL),
  ('Nakakapagpabagabag', 'Dasu feat. Kagamine Len'),
  ('Name of the Game', NULL),
  ('Napalm', NULL),
  ('Native', 'SHK'),
  ('Necromancy', 'Zircon'),
  ('Nemesis', 'M2U'),
  ('Neo Catharsis', 'TAG underground overlay'),
  ('Never Give Up!', NULL),
  ('New Rose', 'Hommarju'),
  ('New World', NULL),
  ('Nightmoves', 'Playmaker'),
  ('NightTheater', 'わかどり'),
  ('Nihilism -Another ver.-', 'nato'),
  ('No Particular Reason', '박미경'),
  ('Nostalgia', '우디'),
  ('Novatail', NULL),
  ('Nyan-turne (feat. KuTiNA)', NULL),
  ('Nyarlathotep', 'nato'),
  ('Oasis', 'KaW'),
  ('Obelisque', 'ESTi x M2U'),
  ('Objection', NULL),
  ('Obliteration', 'ATAS'),
  ('Odin', 'Gram'),
  ('Oh Oh Oh Sexy Vampire', 'Fright Ranger'),
  ('Oh! Rosa (Spanish ver.)', '히든 곡(스텝은 동일)'),
  ('OK? OK!', 'DJ DOC'),
  ('One Step Higher', 'MePuma'),
  ('Only You', '나몰라 패밀리'),
  ('Operator', 'Miss Papaya'),
  ('Orbit Stabilizer', 'DM Ashura'),
  ('Out Of The Ring', '듀스'),
  ('Over the Horizon', 'Yamajet'),
  ('Overblow', 'MAX'),
  ('Overblow2', 'YSJ'),
  ('OVERNIGHT FLOWER', 'P*Light'),
  ('Papasito (feat. KuTiNA)', 'Yakikaze & Cashew'),
  ('Passacaglia', 'Synthwulf'),
  ('Passing Rider', 'mzet:-P'),
  ('Pavane', NULL),
  ('Paved Garden', 'ginkiha'),
  ('Pañuelito Rojo(붉은 손수건)', NULL),
  ('Perpetual', NULL),
  ('Phalanx "RS2018 mix"', 'Cranky'),
  ('Phantom', NULL),
  ('Phantom -Intermezzo-', NULL),
  ('Photosynthesis', 'Zircon'),
  ('Pine Nut', 'Doin'),
  ('pink fuzzy bunnies', 'Wonderboy'),
  ('Playa D'' Embossa (I Feel Love)', 'Paul Sumpter'),
  ('Please', '김건모'),
  ('Pneumonoultramicroscopicsilicovolcanoconiosis ft. Kagamine Len/GUMI', 'Dasu'),
  ('Point Break', NULL),
  ('Point Zero 2', 'Synthwulf'),
  ('Point Zero One', 'Synthwulf'),
  ('Pom Pom Pom', '젝스키스'),
  ('POP SEQUENCE', 'Hommarju'),
  ('Poppin'' Shower', 'P*Light'),
  ('Poseidon', 'Quree'),
  ('Power Trip', 'Nostra Cosa'),
  ('PRiMA MATERiA', 'xi'),
  ('PRIME', 'Tatsh'),
  ('Procedimientos Para Llegar A Un Comun Acuerdo(잘 가 내 사랑)', NULL),
  ('Pull Me Up (Feat. Monya)', 'Applesoda feat. Monya'),
  ('Pump Me Amadeus', NULL),
  ('Punishment Restaurant', 'Memme'),
  ('PUPA', 'モリモリあつし'),
  ('Puyo Puyo', 'U.P'),
  ('Quantum Hyperspace', NULL),
  ('QUATTUORUX', '打打だいず Vs. Tanchiky Vs. からめる'),
  ('Queen Of The Red', 'ETIA.'),
  ('R.I.P.', 'eicateve'),
  ('Ra', 'Banzai'),
  ('Radius', 'KURi-ZiLL'),
  ('Rage of Fire', 'MAX'),
  ('Ragnarok', 'Synthwulf'),
  ('Rapper''s Delight', NULL),
  ('Rave ''til the Earth''s End', '5argon'),
  ('Rave Until The Night Is Over (Cyber Trance Mix)', 'DM Ashura feat. MC Jay and Veronica'),
  ('Re : End of a Dream', 'uma vs. Morimori Atsushi'),
  ('Reality', 'SHK (Feat.Ruriling)'),
  ('Red Blossom', NULL),
  ('Red Snow', 'Cashew'),
  ('Red Swan', 'Yahpp'),
  ('REDLINE', 'Archefluxx'),
  ('Reminiscence', 'MAX'),
  ('Removable Disk0', NULL),
  ('Repentance', 'Abel'),
  ('Requiem', 'MAX'),
  ('Rewind', '이강신'),
  ('Riders, Unite!', 'Andreas Viklund'),
  ('Right Back Up', 'SGX feat. Navi'),
  ('Rise Up (feat. Miori Celesta)', 'Memme feat. Miori Celesta'),
  ('Rising Star', 'M2U'),
  ('Robot Battle', NULL),
  ('Robotix', 'Kbit'),
  ('Rock Robotic -OSX Mix-', 'Oscillator X'),
  ('Rock the House', 'MATDUKE'),
  ('Rolling Christmas', '본작 출시 전 선공개된 음원'),
  ('Round and Round', 'Eskimo & Icebird'),
  ('Run Away', '투야'),
  ('Rush-Hour', NULL),
  ('Rush-More', 'litmus*'),
  ('Réveil α', NULL),
  ('Sad Salsa', '백지영'),
  ('Sarabande', 'MAX'),
  ('Scorpion King', 'r300k'),
  ('See', 'Doin'),
  ('Selfishness', 'S.I.D-Sound'),
  ('Separation With Her', '김현정'),
  ('Set Me Up', NULL),
  ('Shooting Star', 'Coconut'),
  ('Showdown', 'litmus*'),
  ('Shub Niggurath', 'YSJ'),
  ('Silhouette Effect', NULL),
  ('Silver Beat feat. ChisaUezono', 'Tatsh'),
  ('Simon Says, EURODANCE!! (feat. Sara☆M)', 'Jehezukiel☆KAZEMURA☆Hideky'),
  ('Skeptic', 'Doin'),
  ('Slam', '노바소닉'),
  ('Slapstick Parfait', 't+pazolite'),
  ('Slightly', '45RPM'),
  ('Smart Optics', 'Damian Turnbull'),
  ('Smells Like a Chocolate', 'Vospi'),
  ('Smile Diary', 'you'),
  ('Soldiers (TANO*C W TEAM RED ANTHEM)', 'DJ Noriken'),
  ('Solfeggietto', NULL),
  ('Solitary', 'BanYa'),
  ('Solitary 1.5', 'Yahpp'),
  ('Solitary 2', NULL),
  ('Solve My Hurt', 'Doin'),
  ('SONIC BOOM', 'USAO'),
  ('Sora No Shirabe', 'TatshMusicCircle'),
  ('Sorceress Elise', NULL),
  ('Space Fantasy', '이박사'),
  ('Span', 'SGX'),
  ('Spooky Macaron', 'Sobrem'),
  ('STAGER', 'Ras'),
  ('Star Command', 'Zircon'),
  ('Stardream (feat. Romelon)', 'Cashew'),
  ('Stardream -Eurobeat Remix-', 'MAX x Cashew x Dave Rodgers'),
  ('Stardust Overdrive', 'typeMARS'),
  ('Start On Red', 'nato'),
  ('Step On It', 'The DNC'),
  ('STOP! & GO', 'Onyx'),
  ('Style On My Speed Dial', 'Oscillator X'),
  ('Sudden Appearance Image', 'Blacklolita'),
  ('Sudden Romance', 'void'),
  ('Sugar Conspiracy Theory', 'MAX'),
  ('Sugar Plum', 'Mr.Weq'),
  ('Summer -Speedy Mix-', 'Smiley'),
  ('Summer of Love', '룰라'),
  ('Sunshine', 'Playmaker'),
  ('Super Akuma Emperor', 'REDALiCE'),
  ('Super Capriccio', NULL),
  ('Super Fantasy', 'SHK'),
  ('Super Stylin''', 'Warak'),
  ('SUPER☆HARAGURO☆POP', 'Zekk'),
  ('Supremacy', 'KaW'),
  ('Sweet Senorita', 'Miss Papaya'),
  ('Sweet Wonderland', 'MAX'),
  ('Swing Baby', '박진영'),
  ('Swing Baby Swing', 'The DNC'),
  ('Swing the House', 'Elliot Simons'),
  ('Switronic', 'SHK'),
  ('Take My Time', 'Alphadelta'),
  ('Take Out', 'SHK'),
  ('Tales of Pumpnia', 'Applesoda'),
  ('Tantanmen', 'Memme'),
  ('Tek -Club Copenhagen-', NULL),
  ('Tell Me A Story (Compendium Mix)', 'SGX'),
  ('Tell Me Tell Me', 'S'),
  ('Telling Fortune Flower', 'Koharu feat.Renyata'),
  ('Temptation', '하리수'),
  ('Tension', 'Inspector K'),
  ('Tepris', 'Doin'),
  ('Terminal', 'Sanxion7'),
  ('That Kitty (PIU Edit)', NULL),
  ('The Apocalypse', 'HyuN'),
  ('The Devil', NULL),
  ('The End of the World ft. Skizzo', 'MonstDeath'),
  ('The Festival of Ghost 2 (Sneak)', 'YSJ'),
  ('The Game of Love', 'Jenny Rom'),
  ('The Last Firstborn', 'Celldweller'),
  ('The Last Rebellion', 'MonstDeath'),
  ('The Neon Underground', 'Oscillator X'),
  ('The Next Step', 'Falling Down'),
  ('The People Didn''t Know', 'Banya Production'),
  ('The Quick Brown Fox Jumps Over The Lazy Dog', 'YSJ'),
  ('the RAP(act.2)', '허니 패밀리'),
  ('The Reverie', 'uma'),
  ('The Revolution', 'MAX&DOOM'),
  ('The Waves', 'UN'),
  ('Throw''em Up', NULL),
  ('Till the end of time', NULL),
  ('Time Attack <BLUE>', 'r300k'),
  ('Time To Say Goodbye', '소찬휘'),
  ('Timing', '하이틴'),
  ('Transacaglia in G-minor', 'ATAS'),
  ('Trash Man', '넥스트'),
  ('Travel to Future', 'Neutral Moon'),
  ('Tribal Style', 'KaW'),
  ('Tribe Attacker', 'Hi-G'),
  ('TRICKL4SH 220', 'Lite Show Magic'),
  ('Tritium', 'Irelriser'),
  ('Tropicanic', 'SHK'),
  ('Trotpris', 'Doin'),
  ('Turkey March', NULL),
  ('Turkey March -Minimal Tunes-', NULL),
  ('Twist of Fate (feat. Ruriling)', 'Jehezukiel'),
  ('U Got 2 Know', 'MAX'),
  ('U Got Me Crazy', NULL),
  ('U Got Me Rocking', NULL),
  ('UFO Catcher', 'Initial P'),
  ('Ugly Dee', NULL),
  ('Ultimate Eyes', NULL),
  ('ULTIMATUM', NULL),
  ('Ultramania', '서태지'),
  ('Underworld ft. Skizzo (PIU Edit)', NULL),
  ('Unfelicitas', 'Fiverwater'),
  ('Unforgettable Memory', '서태지가 직접 게임사이즈 편집'),
  ('Unique', 'SHK'),
  ('Unlikely (Stay With Me)', 'Celldweller'),
  ('Uranium', 'Memme'),
  ('Utopia', 'Smiley'),
  ('Utsushiyo no Kaze feat. Kana', 'MiLa'),
  ('V3', 'YSJ'),
  ('Vacuum', 'Doin'),
  ('VANISH', 'Applesoda'),
  ('Vanish 2 - Roar of the invisible dragon', 'Applesoda'),
  ('VECTOR', 'Zekk'),
  ('Versailles', 'HyuN & MIIM'),
  ('Video Out C', 'Vospi'),
  ('Violet Perfume', NULL),
  ('Visual Dream 2 (In Fiction)', 'Aragon'),
  ('Viyella''s Nightmare', 'Laur'),
  ('Vook', NULL),
  ('VVV (VerTex^3)', 'ZiGZaG'),
  ('Wake Up', 'Kid Whatever'),
  ('Walkie Talkie Man', NULL),
  ('Waltz of Doge', 'Cashew'),
  ('Wanting You', 'Ekowraith'),
  ('Wayo Wayo', 'O.P.P.A'),
  ('We Are Loud', 'Dynamedion'),
  ('We Got 2 Know', NULL),
  ('We Love Your Step', 'EmoCosine'),
  ('We Will Meet Again', NULL),
  ('Wedding Crashers', 'SHK'),
  ('Wham Bam Boogie', 'Bambee'),
  ('What Happened', 'Throwdown'),
  ('While Tha Rekkid Spinz', 'DJ Zombie'),
  ('Who', 'KaW'),
  ('Wicked Legend', 'D_AAN'),
  ('Will o'' The Wisp', NULL),
  ('Windmill', 'yak_won'),
  ('Winter', 'BanYa'),
  ('Wish You Could Find', '유승준'),
  ('Witch Doctor', NULL),
  ('Witch Doctor #1', 'Yahpp'),
  ('wither garden', 'uma feat. Kanon Tachibana'),
  ('X-Rave', 'DM Ashura'),
  ('X-Tream', NULL),
  ('Xenesis', NULL),
  ('Xeroize', 'FE'),
  ('Xtree', 'Yahpp'),
  ('Xuxa', 'Smiley'),
  ('Y', '김건모'),
  ('Yeo Rae A', 'S.I.D-Sound'),
  ('Yo! Say!! Fairy!!!', 'MYUKKE.'),
  ('Yog-Sothoth', 'nato'),
  ('Yoropiku Pikuyoro!', '바쿠스테 소토칸다 잇초메'),
  ('You again my love', 'CYO Style'),
  ('YOU AND I', '드림캐쳐'),
  ('You Bring The Rain', 'Oscillator X'),
  ('Your Mind', 'Roy Mikelate'),
  ('Z -The New Legend-', 'DM Ashura'),
  ('Zodiac', 'Banzai'),
  ('Zzanga', '김건모'),
  ('†DOOF†SENC†', 'Kobaryo'),
  ('刻限回廊ラビリンス', NULL),
  ('고민중독 (T.B.H)', 'QWER'),
  ('날아올라', '드림캐쳐'),
  ('붕붕(Feat. 식케이) (Prod. GroovyRoom)', 'HAON'),
  ('비행기', '타이푼'),
  ('빌려온 고양이 (Do the Dance)', 'ILLIT'),
  ('아마이 유우와쿠 데인져러스', '바쿠스테 소토칸다 잇쵸메'),
  ('연애용자', 'Last Note.'),
  ('익스트림 음악학원 1교시 feat. Nanahira', 'Massive New Krew & RoughSketch'),
  ('익스트림 음악학원 2교시 feat. Nanahira', NULL),
  ('일 더하기 일은 귀요미', 'Memme'),
  ('조깅', '루시'),
  ('천년이 지나서', 'TOTO'),
  ('호랑풍류가', '상록수 feat. 하나나')
) AS v(title, artist)
ON CONFLICT (machine_id, title) DO NOTHING;

-- 대소문자만 다른 중복 정리.
-- (machine_id, title) UNIQUE 는 대소문자를 구분하므로 시드의
-- 'Love is a Danger Zone pt.2' 와 문서의 'Love is A Danger Zone pt.2' 가 둘 다
-- 들어간다. 채보가 붙지 않은 쪽(=이 파일로 들어온 쪽)만 지운다.
DELETE FROM songs d
WHERE d.machine_id = 1
  AND NOT EXISTS (SELECT 1 FROM charts c WHERE c.song_id = d.id)
  AND EXISTS (
    SELECT 1 FROM songs k
     WHERE k.machine_id = d.machine_id
       AND k.id <> d.id
       AND lower(k.title) = lower(d.title)
       AND EXISTS (SELECT 1 FROM charts c WHERE c.song_id = k.id)
  );
